version: '3.8'
services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile

    env_file:
      - ./back/.env

    container_name: api_container_test
    ports:
      - "${PORT_BACK=3001:-3001}:${PORT_BACK=3001:-3001}"
    depends_on:
      - db
    environment:
      - PORT=${PORT_BACK=3001}  
      - DATABASE_URL=${DATABASE_URL_PROD}
    restart: always
    command: >
      /bin/sh -c "wait-for-it db:5432 -- 
      && npm start"

  db:
    image: postgres
    container_name: postgres_container_test
    environment:
      POSTGRES_USER: megaJunior
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jubileutaskapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./front/.env

    container_name: front_container
    ports:
      - "${PORT_FRONT:-3002}:${PORT_FRONT:-3002}"
    depends_on:
      - api
      - db
      
volumes:
  pgdata:
